name: Notion Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, closed]

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Register Commit to Notion
        if: github.event_name == 'push'
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          commits=$(jq -c '.commits[]' <<< $GITHUB_EVENT_PATH)
          for commit in $commits; do
            message=$(jq -r '.message' <<< $commit)
            url=$(jq -r '.url' <<< $commit)
            payload=$(jq -n \
              --arg title "$message" \
              --arg url "$url" \
              --arg state "Commit" \
              '{
                "parent": {"database_id": env.NOTION_DATABASE_ID},
                "properties": {
                  "Name": {
                    "title": [
                      {
                        "text": {
                          "content": $title
                        }
                      }
                    ]
                  },
                  "Descripción": {
                    "rich_text": [
                      {
                        "text": {
                          "content": $url
                        }
                      }
                    ]
                  },
                  "Estado": {
                    "select": {
                      "name": $state
                    }
                  }
                }
              }'
            )
            curl -X POST "https://api.notion.com/v1/pages" \
              -H "Authorization: Bearer $NOTION_TOKEN" \
              -H "Content-Type: application/json" \
              -H "Notion-Version: 2022-06-28" \
              -d "$payload"
          done

      - name: Register Pull Request to Notion
        if: github.event_name == 'pull_request'
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          pr_title=${{ github.event.pull_request.title }}
          pr_url=${{ github.event.pull_request.html_url }}
          pr_state=${{ github.event.action }}
          payload=$(jq -n \
            --arg title "$pr_title" \
            --arg url "$pr_url" \
            --arg state "Pull Request" \
            '{
              "parent": {"database_id": env.NOTION_DATABASE_ID},
              "properties": {
                "Name": {
                  "title": [
                    {
                      "text": {
                        "content": $title
                      }
                    }
                  ]
                },
                "Descripción": {
                  "rich_text": [
                    {
                      "text": {
                        "content": $url
                      }
                    }
                  ]
                },
                "Estado": {
                  "select": {
                    "name": $state
                  }
                }
              }
            }'
          )
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            -d "$payload"
