name: Sync Commits to Notion

on:
  push:
    branches:
      - main  # Ajusta según la rama de tu repositorio

jobs:
  notion_hook_job:
    runs-on: ubuntu-latest
    name: Sync Commits to Notion Database
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sync to Notion
        id: notion
        uses: alessandrobelli/NotionHook@1.1
        with:
          notion_secret: ${{ secrets.NOTION_SECRET }}
          notion_database: ${{ secrets.NOTION_DATABASE }}
